export const ANIMATION_TIMING_MS = {
  MODAL_CLOSE: 1500,
  MODAL_TRANSITION: 2000,
  INITIAL_DEAL: 2000,
  DEAL: 1000,
  DEAL_DELAY: 500,
} as const;

export const ANIMATION_TIMING_SEC = {
  DEAL_DELAY: ANIMATION_TIMING_MS.DEAL_DELAY / 1000,
}
 