@baseUrl = http://localhost:3000/api

###
# @name matchCreate
Post {{baseUrl}}/matches Http/1.1
content-type: application/json

{
    "userIds": ["userId1", "userId2"]
}

###
# @name matchGetSummary
Get {{baseUrl}}/matches/{{matchCreate.response.body.$.id}}/summary Http/1.1

@playerId = {{matchGetSummary.response.body.$.players[0].id}}

###
# @name matchStartRound
Post {{baseUrl}}/matches/{{matchCreate.response.body.$.id}}/start-round Http/1.1

###
# @name matchBet
Post {{baseUrl}}/matches/{{matchCreate.response.body.$.id}}/players/{{playerId}}/bet Http/1.1
content-type: application/json

{
    "amount": 100
}

###
# @name matchHit
Post {{baseUrl}}/matches/{{matchCreate.response.body.$.id}}/hit Http/1.1

###
# @name matchStand
Post {{baseUrl}}/matches/{{matchCreate.response.body.$.id}}/stand Http/1.1

###
# @name matchCompleteRound
Post {{baseUrl}}/matches/{{matchCreate.response.body.$.id}}/complete-round Http/1.1

###
# @name matchGetRoundResult
Get {{baseUrl}}/matches/{{matchCreate.response.body.$.id}}/round-result Http/1.1

###
# @name matchGetResult
Get {{baseUrl}}/matches/{{matchCreate.response.body.$.id}}/result Http/1.1
